jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Download Hugo
      run: |
        wget -c 'https://github.com/gohugoio/hugo/releases/download/v${{ env.hugoVersion }}/hugo_extended_${{ env.hugoVersion }}_Linux-64bit.deb'
    - name: Install Hugo
      run: |
        sudo dpkg -i hugo_extended_${{ env.hugoVersion }}_Linux-64bit.deb
    - name: Generate Blog
      run: |
        hugo --log -v
    
    # Prevent hugo deploy from deleting files with '--maxDeletes -1'
    - name: Deploy Blog
      run: |
        hugo deploy --maxDeletes -1
      env:
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        AZURE_STORAGE_ACCOUNT: ${{ env.StorageAccount }}
