name = "Nicholas Chang"
license = "MIT"
licenselink = "https://github.com/Track3/hermit/blob/master/LICENSE"
description = "Hi, I'am Nicholas :)."
homepage = "https://github.com/Track3/hermit"
tags = ["blog", "minimal", "dark", "responsive"]
features = [
  "single column",
  "featured image",
  "social icons",
  "google analytics",
  "disqus"
]
min_version = 0.43

[author]
  name = "Track3"
  homepage = "https://stshelldataprd1.z6.web.core.windows.net/"
