name: deploy_frontend

# Deploy when push made from frontend folder.
on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name stshelldataprd1 -d '$web' -s frontend/
    
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az cdn endpoint purge --content-paths "/*" --resource-group rg-web-prd-cloudresume --profile-name career-site --name nicholaschang
          
  # Azure logout 
    - name: logout
      run: |
            az logout