name: deploy_frontend
# Deploys when push is made from frontend folder

on:
    push:
        branches: [ main ]
        paths: 
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - name: login with azure 
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
            az storage blob delete-batch -s "\$web" --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
            az storage blob upload-batch -d "\$web" -s frontend/ --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
           az cdn endpoint purge -n ${{ secrets.AZURE_CDN_ENDPOINT }} --profile-name ${{ secrets.AZURE_CDN_PROFILE_NAME }} --content-paths "/*" --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --no-wait  # Azure logout 
    - name: logout
      run: |
            az logout