name: "Build and Test Frontend"

on:
  push:
    branches:
    - 'path-check'
    paths:
    - 'frontend/**'
    - '.github/workflows/**'

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo Hello world